### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by hhhxiao** [hhhxiao/trapdoor-ll#6]
- [x] High-precision entity data display( #37 )
- [x] refactor hopper counter ( #38 )
- [x] `player drop` command
- [x] `trapdoor dump` command
- [x] `dis` command
- [x]  block roration
- [x] `slime` command
- [x]  comfig file hot load
- [x]  `crashserver <toeken:string>`
- [x] simplayer auto-join

**Comment by XCLHove** [comment]
能否添加一个配置用于选择是否添加前缀bot_

**Comment by hhhxiao** [comment]
> 能否添加一个配置用于选择是否添加前缀bot_

把配置文件的`"bot_"`改成:`""`就行了

**Comment by XCLHove** [comment]
> > 能否添加一个配置用于选择是否添加前缀bot_
> 
> 把配置文件的`"bot_"`改成:`""`就行了

ok
